apiVersion: v1
kind: Pod
metadata:
  name: bs
  labels:
    app: web
spec:
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
    containers:
      - name: bs
        image: newcl/bs:latest
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        ports:
          - containerPort: 7788
            protocol: UDP