// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b.proto

package info.chenliang.b.message;

public interface JoinOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Join)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room = 1;</code>
   */
  int getRoom();

  /**
   * <code>string user = 2;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>int32 subPort = 3;</code>
   */
  int getSubPort();

  /**
   * <code>int32 subStreamId = 4;</code>
   */
  int getSubStreamId();

  /**
   * <code>string ip = 5;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 5;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();
}
