// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b.proto

package info.chenliang.b.message;

public interface MessageWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Join join = 1;</code>
   */
  boolean hasJoin();
  /**
   * <code>.Join join = 1;</code>
   */
  info.chenliang.b.message.Join getJoin();
  /**
   * <code>.Join join = 1;</code>
   */
  info.chenliang.b.message.JoinOrBuilder getJoinOrBuilder();

  /**
   * <code>.JoinResult joinResult = 2;</code>
   */
  boolean hasJoinResult();
  /**
   * <code>.JoinResult joinResult = 2;</code>
   */
  info.chenliang.b.message.JoinResult getJoinResult();
  /**
   * <code>.JoinResult joinResult = 2;</code>
   */
  info.chenliang.b.message.JoinResultOrBuilder getJoinResultOrBuilder();

  /**
   * <code>.MoveToPosition action = 3;</code>
   */
  boolean hasAction();
  /**
   * <code>.MoveToPosition action = 3;</code>
   */
  info.chenliang.b.message.MoveToPosition getAction();
  /**
   * <code>.MoveToPosition action = 3;</code>
   */
  info.chenliang.b.message.MoveToPositionOrBuilder getActionOrBuilder();

  public info.chenliang.b.message.MessageWrapper.MsgCase getMsgCase();
}
