// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b.proto

package info.chenliang.b.message;

/**
 * Protobuf type {@code MessageWrapper}
 */
public  final class MessageWrapper extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MessageWrapper)
    MessageWrapperOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageWrapper.newBuilder() to construct.
  private MessageWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageWrapper() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageWrapper(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            info.chenliang.b.message.Join.Builder subBuilder = null;
            if (msgCase_ == 1) {
              subBuilder = ((info.chenliang.b.message.Join) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(info.chenliang.b.message.Join.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((info.chenliang.b.message.Join) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 1;
            break;
          }
          case 18: {
            info.chenliang.b.message.JoinResult.Builder subBuilder = null;
            if (msgCase_ == 2) {
              subBuilder = ((info.chenliang.b.message.JoinResult) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(info.chenliang.b.message.JoinResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((info.chenliang.b.message.JoinResult) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 2;
            break;
          }
          case 26: {
            info.chenliang.b.message.MoveToPosition.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((info.chenliang.b.message.MoveToPosition) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(info.chenliang.b.message.MoveToPosition.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((info.chenliang.b.message.MoveToPosition) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.chenliang.b.message.B.internal_static_MessageWrapper_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.chenliang.b.message.B.internal_static_MessageWrapper_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.chenliang.b.message.MessageWrapper.class, info.chenliang.b.message.MessageWrapper.Builder.class);
  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite {
    JOIN(1),
    JOINRESULT(2),
    ACTION(3),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1: return JOIN;
        case 2: return JOINRESULT;
        case 3: return ACTION;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int JOIN_FIELD_NUMBER = 1;
  /**
   * <code>.Join join = 1;</code>
   */
  public boolean hasJoin() {
    return msgCase_ == 1;
  }
  /**
   * <code>.Join join = 1;</code>
   */
  public info.chenliang.b.message.Join getJoin() {
    if (msgCase_ == 1) {
       return (info.chenliang.b.message.Join) msg_;
    }
    return info.chenliang.b.message.Join.getDefaultInstance();
  }
  /**
   * <code>.Join join = 1;</code>
   */
  public info.chenliang.b.message.JoinOrBuilder getJoinOrBuilder() {
    if (msgCase_ == 1) {
       return (info.chenliang.b.message.Join) msg_;
    }
    return info.chenliang.b.message.Join.getDefaultInstance();
  }

  public static final int JOINRESULT_FIELD_NUMBER = 2;
  /**
   * <code>.JoinResult joinResult = 2;</code>
   */
  public boolean hasJoinResult() {
    return msgCase_ == 2;
  }
  /**
   * <code>.JoinResult joinResult = 2;</code>
   */
  public info.chenliang.b.message.JoinResult getJoinResult() {
    if (msgCase_ == 2) {
       return (info.chenliang.b.message.JoinResult) msg_;
    }
    return info.chenliang.b.message.JoinResult.getDefaultInstance();
  }
  /**
   * <code>.JoinResult joinResult = 2;</code>
   */
  public info.chenliang.b.message.JoinResultOrBuilder getJoinResultOrBuilder() {
    if (msgCase_ == 2) {
       return (info.chenliang.b.message.JoinResult) msg_;
    }
    return info.chenliang.b.message.JoinResult.getDefaultInstance();
  }

  public static final int ACTION_FIELD_NUMBER = 3;
  /**
   * <code>.MoveToPosition action = 3;</code>
   */
  public boolean hasAction() {
    return msgCase_ == 3;
  }
  /**
   * <code>.MoveToPosition action = 3;</code>
   */
  public info.chenliang.b.message.MoveToPosition getAction() {
    if (msgCase_ == 3) {
       return (info.chenliang.b.message.MoveToPosition) msg_;
    }
    return info.chenliang.b.message.MoveToPosition.getDefaultInstance();
  }
  /**
   * <code>.MoveToPosition action = 3;</code>
   */
  public info.chenliang.b.message.MoveToPositionOrBuilder getActionOrBuilder() {
    if (msgCase_ == 3) {
       return (info.chenliang.b.message.MoveToPosition) msg_;
    }
    return info.chenliang.b.message.MoveToPosition.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgCase_ == 1) {
      output.writeMessage(1, (info.chenliang.b.message.Join) msg_);
    }
    if (msgCase_ == 2) {
      output.writeMessage(2, (info.chenliang.b.message.JoinResult) msg_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (info.chenliang.b.message.MoveToPosition) msg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (info.chenliang.b.message.Join) msg_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (info.chenliang.b.message.JoinResult) msg_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (info.chenliang.b.message.MoveToPosition) msg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.chenliang.b.message.MessageWrapper)) {
      return super.equals(obj);
    }
    info.chenliang.b.message.MessageWrapper other = (info.chenliang.b.message.MessageWrapper) obj;

    boolean result = true;
    result = result && getMsgCase().equals(
        other.getMsgCase());
    if (!result) return false;
    switch (msgCase_) {
      case 1:
        result = result && getJoin()
            .equals(other.getJoin());
        break;
      case 2:
        result = result && getJoinResult()
            .equals(other.getJoinResult());
        break;
      case 3:
        result = result && getAction()
            .equals(other.getAction());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (msgCase_) {
      case 1:
        hash = (37 * hash) + JOIN_FIELD_NUMBER;
        hash = (53 * hash) + getJoin().hashCode();
        break;
      case 2:
        hash = (37 * hash) + JOINRESULT_FIELD_NUMBER;
        hash = (53 * hash) + getJoinResult().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ACTION_FIELD_NUMBER;
        hash = (53 * hash) + getAction().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.chenliang.b.message.MessageWrapper parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.chenliang.b.message.MessageWrapper parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.chenliang.b.message.MessageWrapper parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.chenliang.b.message.MessageWrapper parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.chenliang.b.message.MessageWrapper prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MessageWrapper}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MessageWrapper)
      info.chenliang.b.message.MessageWrapperOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.chenliang.b.message.B.internal_static_MessageWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.chenliang.b.message.B.internal_static_MessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.chenliang.b.message.MessageWrapper.class, info.chenliang.b.message.MessageWrapper.Builder.class);
    }

    // Construct using info.chenliang.b.message.MessageWrapper.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.chenliang.b.message.B.internal_static_MessageWrapper_descriptor;
    }

    @java.lang.Override
    public info.chenliang.b.message.MessageWrapper getDefaultInstanceForType() {
      return info.chenliang.b.message.MessageWrapper.getDefaultInstance();
    }

    @java.lang.Override
    public info.chenliang.b.message.MessageWrapper build() {
      info.chenliang.b.message.MessageWrapper result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.chenliang.b.message.MessageWrapper buildPartial() {
      info.chenliang.b.message.MessageWrapper result = new info.chenliang.b.message.MessageWrapper(this);
      if (msgCase_ == 1) {
        if (joinBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = joinBuilder_.build();
        }
      }
      if (msgCase_ == 2) {
        if (joinResultBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = joinResultBuilder_.build();
        }
      }
      if (msgCase_ == 3) {
        if (actionBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = actionBuilder_.build();
        }
      }
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.chenliang.b.message.MessageWrapper) {
        return mergeFrom((info.chenliang.b.message.MessageWrapper)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.chenliang.b.message.MessageWrapper other) {
      if (other == info.chenliang.b.message.MessageWrapper.getDefaultInstance()) return this;
      switch (other.getMsgCase()) {
        case JOIN: {
          mergeJoin(other.getJoin());
          break;
        }
        case JOINRESULT: {
          mergeJoinResult(other.getJoinResult());
          break;
        }
        case ACTION: {
          mergeAction(other.getAction());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.chenliang.b.message.MessageWrapper parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.chenliang.b.message.MessageWrapper) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        info.chenliang.b.message.Join, info.chenliang.b.message.Join.Builder, info.chenliang.b.message.JoinOrBuilder> joinBuilder_;
    /**
     * <code>.Join join = 1;</code>
     */
    public boolean hasJoin() {
      return msgCase_ == 1;
    }
    /**
     * <code>.Join join = 1;</code>
     */
    public info.chenliang.b.message.Join getJoin() {
      if (joinBuilder_ == null) {
        if (msgCase_ == 1) {
          return (info.chenliang.b.message.Join) msg_;
        }
        return info.chenliang.b.message.Join.getDefaultInstance();
      } else {
        if (msgCase_ == 1) {
          return joinBuilder_.getMessage();
        }
        return info.chenliang.b.message.Join.getDefaultInstance();
      }
    }
    /**
     * <code>.Join join = 1;</code>
     */
    public Builder setJoin(info.chenliang.b.message.Join value) {
      if (joinBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        joinBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Join join = 1;</code>
     */
    public Builder setJoin(
        info.chenliang.b.message.Join.Builder builderForValue) {
      if (joinBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        joinBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Join join = 1;</code>
     */
    public Builder mergeJoin(info.chenliang.b.message.Join value) {
      if (joinBuilder_ == null) {
        if (msgCase_ == 1 &&
            msg_ != info.chenliang.b.message.Join.getDefaultInstance()) {
          msg_ = info.chenliang.b.message.Join.newBuilder((info.chenliang.b.message.Join) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 1) {
          joinBuilder_.mergeFrom(value);
        }
        joinBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.Join join = 1;</code>
     */
    public Builder clearJoin() {
      if (joinBuilder_ == null) {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
        }
        joinBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.Join join = 1;</code>
     */
    public info.chenliang.b.message.Join.Builder getJoinBuilder() {
      return getJoinFieldBuilder().getBuilder();
    }
    /**
     * <code>.Join join = 1;</code>
     */
    public info.chenliang.b.message.JoinOrBuilder getJoinOrBuilder() {
      if ((msgCase_ == 1) && (joinBuilder_ != null)) {
        return joinBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 1) {
          return (info.chenliang.b.message.Join) msg_;
        }
        return info.chenliang.b.message.Join.getDefaultInstance();
      }
    }
    /**
     * <code>.Join join = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.chenliang.b.message.Join, info.chenliang.b.message.Join.Builder, info.chenliang.b.message.JoinOrBuilder> 
        getJoinFieldBuilder() {
      if (joinBuilder_ == null) {
        if (!(msgCase_ == 1)) {
          msg_ = info.chenliang.b.message.Join.getDefaultInstance();
        }
        joinBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.chenliang.b.message.Join, info.chenliang.b.message.Join.Builder, info.chenliang.b.message.JoinOrBuilder>(
                (info.chenliang.b.message.Join) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 1;
      onChanged();;
      return joinBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        info.chenliang.b.message.JoinResult, info.chenliang.b.message.JoinResult.Builder, info.chenliang.b.message.JoinResultOrBuilder> joinResultBuilder_;
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    public boolean hasJoinResult() {
      return msgCase_ == 2;
    }
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    public info.chenliang.b.message.JoinResult getJoinResult() {
      if (joinResultBuilder_ == null) {
        if (msgCase_ == 2) {
          return (info.chenliang.b.message.JoinResult) msg_;
        }
        return info.chenliang.b.message.JoinResult.getDefaultInstance();
      } else {
        if (msgCase_ == 2) {
          return joinResultBuilder_.getMessage();
        }
        return info.chenliang.b.message.JoinResult.getDefaultInstance();
      }
    }
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    public Builder setJoinResult(info.chenliang.b.message.JoinResult value) {
      if (joinResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        joinResultBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    public Builder setJoinResult(
        info.chenliang.b.message.JoinResult.Builder builderForValue) {
      if (joinResultBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        joinResultBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    public Builder mergeJoinResult(info.chenliang.b.message.JoinResult value) {
      if (joinResultBuilder_ == null) {
        if (msgCase_ == 2 &&
            msg_ != info.chenliang.b.message.JoinResult.getDefaultInstance()) {
          msg_ = info.chenliang.b.message.JoinResult.newBuilder((info.chenliang.b.message.JoinResult) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 2) {
          joinResultBuilder_.mergeFrom(value);
        }
        joinResultBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    public Builder clearJoinResult() {
      if (joinResultBuilder_ == null) {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
        }
        joinResultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    public info.chenliang.b.message.JoinResult.Builder getJoinResultBuilder() {
      return getJoinResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    public info.chenliang.b.message.JoinResultOrBuilder getJoinResultOrBuilder() {
      if ((msgCase_ == 2) && (joinResultBuilder_ != null)) {
        return joinResultBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 2) {
          return (info.chenliang.b.message.JoinResult) msg_;
        }
        return info.chenliang.b.message.JoinResult.getDefaultInstance();
      }
    }
    /**
     * <code>.JoinResult joinResult = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.chenliang.b.message.JoinResult, info.chenliang.b.message.JoinResult.Builder, info.chenliang.b.message.JoinResultOrBuilder> 
        getJoinResultFieldBuilder() {
      if (joinResultBuilder_ == null) {
        if (!(msgCase_ == 2)) {
          msg_ = info.chenliang.b.message.JoinResult.getDefaultInstance();
        }
        joinResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.chenliang.b.message.JoinResult, info.chenliang.b.message.JoinResult.Builder, info.chenliang.b.message.JoinResultOrBuilder>(
                (info.chenliang.b.message.JoinResult) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 2;
      onChanged();;
      return joinResultBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        info.chenliang.b.message.MoveToPosition, info.chenliang.b.message.MoveToPosition.Builder, info.chenliang.b.message.MoveToPositionOrBuilder> actionBuilder_;
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    public boolean hasAction() {
      return msgCase_ == 3;
    }
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    public info.chenliang.b.message.MoveToPosition getAction() {
      if (actionBuilder_ == null) {
        if (msgCase_ == 3) {
          return (info.chenliang.b.message.MoveToPosition) msg_;
        }
        return info.chenliang.b.message.MoveToPosition.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return actionBuilder_.getMessage();
        }
        return info.chenliang.b.message.MoveToPosition.getDefaultInstance();
      }
    }
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    public Builder setAction(info.chenliang.b.message.MoveToPosition value) {
      if (actionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        actionBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    public Builder setAction(
        info.chenliang.b.message.MoveToPosition.Builder builderForValue) {
      if (actionBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        actionBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    public Builder mergeAction(info.chenliang.b.message.MoveToPosition value) {
      if (actionBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != info.chenliang.b.message.MoveToPosition.getDefaultInstance()) {
          msg_ = info.chenliang.b.message.MoveToPosition.newBuilder((info.chenliang.b.message.MoveToPosition) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          actionBuilder_.mergeFrom(value);
        }
        actionBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    public Builder clearAction() {
      if (actionBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        actionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    public info.chenliang.b.message.MoveToPosition.Builder getActionBuilder() {
      return getActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    public info.chenliang.b.message.MoveToPositionOrBuilder getActionOrBuilder() {
      if ((msgCase_ == 3) && (actionBuilder_ != null)) {
        return actionBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (info.chenliang.b.message.MoveToPosition) msg_;
        }
        return info.chenliang.b.message.MoveToPosition.getDefaultInstance();
      }
    }
    /**
     * <code>.MoveToPosition action = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        info.chenliang.b.message.MoveToPosition, info.chenliang.b.message.MoveToPosition.Builder, info.chenliang.b.message.MoveToPositionOrBuilder> 
        getActionFieldBuilder() {
      if (actionBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = info.chenliang.b.message.MoveToPosition.getDefaultInstance();
        }
        actionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            info.chenliang.b.message.MoveToPosition, info.chenliang.b.message.MoveToPosition.Builder, info.chenliang.b.message.MoveToPositionOrBuilder>(
                (info.chenliang.b.message.MoveToPosition) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return actionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MessageWrapper)
  }

  // @@protoc_insertion_point(class_scope:MessageWrapper)
  private static final info.chenliang.b.message.MessageWrapper DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.chenliang.b.message.MessageWrapper();
  }

  public static info.chenliang.b.message.MessageWrapper getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageWrapper>
      PARSER = new com.google.protobuf.AbstractParser<MessageWrapper>() {
    @java.lang.Override
    public MessageWrapper parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageWrapper(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageWrapper> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageWrapper> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.chenliang.b.message.MessageWrapper getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

