// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b.proto

package info.chenliang.b.message;

public interface MoveToPositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MoveToPosition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Position position = 1;</code>
   */
  boolean hasPosition();
  /**
   * <code>.Position position = 1;</code>
   */
  info.chenliang.b.message.Position getPosition();
  /**
   * <code>.Position position = 1;</code>
   */
  info.chenliang.b.message.PositionOrBuilder getPositionOrBuilder();
}
